export const TimerStyles = {
  WORK_SESSION_BACKGROUND: '#FFFFFF',
  SHORT_BREAK_BACKGROUND: '#FEF9C7',
  LONG_BREAK_BACKGROUND: '#FCE181',
};

export const TaskStyles = {
  UNSELECTED_TASK_BACKGROUND: '#FFFBF6',
  SELECTED_TASK_BORDER: '3px solid #03abee',
  UNSELECTED_TASK_BORDER: 'none',
  SELECTED_TASK_BORDER_RADIUS: '30px',
  SELECTED_TASK_TOP_OFFSET: '3px',
  UNSELECTED_TASK_TOP_OFFSET: '0px',
  BOX_SHADOW: '0 12px 24px 0 rgba(0, 0, 0, 0.22), 0 12px 24px 0 rgba(0, 0, 0, 0.22)',
  NO_BOX_SHADOW: '0px 0px',
};
