plugins:
  - jest
env:
  browser: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "airbnb"
rules:
  no-use-before-define: 
    - error
    - functions: false
      classes: true
      variables: true
  max-len:
    - error
    - code: 120
  import/extensions:
    - warn
    - always
  no-param-reassign:
    - error
    - props: false
  no-new:
    - warn
  no-unused-expressions:
    - warn
  no-underscore-dangle:
    - warn
  no-mixed-operators:
    - off
  no-case-declarations:
    - warn
