name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      working-directory: ./source\
      - run: npm run build
      
  test:
    runs-on: ubuntu-latest
    
    steps:
      working-directory: ./source
      - run: npm run test
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
      working-directory: ./source
      - run: npm run lint
