name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    working-directory: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
      
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
